name: weather_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.1
  json_annotation: ^4.8.1
  dio: ^5.3.3
  get_it: ^7.6.4
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.2

dev_dependencies: 
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.7.1

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/envs/
